name: Build (Windows)

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  schedule:
    # Build once every fortnight
    - cron: "10 4 1,15 * *"

permissions:
  contents: write

jobs:
  build:
    name: "Build Windows Binary"
    strategy:
      matrix:
        win_ver: ["win32", "win64"]
        include:
          - win_ver: win32
            vs_arch: "Win32"
          - win_ver: win64
            vs_arch: "x64"

    runs-on: windows-2022
    env:
      PRESET_NAME: msvc-2022

    steps:
      - name: "‚è≥ Clone repo..."
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "üñºÔ∏è Setup scene..."
        shell: bash
        run: |
          true

      - name: Restore CPM dependencies
        id: cache-cpm-deps
        uses: actions/cache/restore@v3
        with:
          path: |
            out/cache-cpm
            out/build/${{ env.PRESET_NAME }}/_deps
          key: ${{ runner.os }}-cpm-${{ matrix.win_ver }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cpm-${{ hashFiles('CMakeLists.txt') }}
            ${{ runner.os }}-cpm-

      - name: "üîß CMake: Configure"
        shell: bash
        run: cmake --preset "${{ env.PRESET_NAME }}" -A "${{ matrix.vs_arch }}"

      - name: "üõ†Ô∏è CMake: Build"
        shell: bash
        run: cmake --build --preset "${{ env.PRESET_NAME }}-release"

      - name: Save CPM dependencies
        id: cache-cpm-deps-save
        uses: actions/cache/save@v3
        with:
          path: |
            out/cache-cpm
            out/build/${{ env.PRESET_NAME }}/_deps
          key: ${{ steps.cache-cpm-deps.outputs.cache-primary-key }}

      - name: "üí£ Test um-crypto ..."
        shell: bash
        run: ctest --preset "${{ env.PRESET_NAME }}-release" --output-on-failure

      - name: "üì¶ Package static libs..."
        shell: bash
        run: |
          DIST_SOURCE="dist/libparakeet-${{ matrix.win_ver }}/"
          mkdir -p "${DIST_SOURCE}/libparakeet"
          cp -R "out/build/$PRESET_NAME/Release" "${DIST_SOURCE}/libparakeet/lib"
          cp -R include "${DIST_SOURCE}/libparakeet"
          cp README.md CHANGELOG.md LICENSE.txt "${DIST_SOURCE}"

      - name: "üöÄ Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "libparakeet-${{ matrix.win_ver }}"
          path: dist/

      - name: "üóúÔ∏è Packaging"
        working-directory: dist
        shell: pwsh
        run: Compress-Archive "../libparakeet-${{ matrix.win_ver }}.zip" -Path *

      - name: üìù Draft Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "<to be filled>"
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: "*.zip"
