name: Build (Windows)

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  schedule:
    # Build once every fortnight
    - cron: "10 4 1,15 * *"

permissions:
  contents: write

jobs:
  build:
    name: "Build Windows Binary"
    strategy:
      matrix:
        win_ver: ["win32", "win64"]
        include:
          - win_ver: win32
            vs_arch: "Win32"
          - win_ver: win64
            vs_arch: "x64"

    runs-on: windows-2022
    env:
      PRESET_NAME: msvc-2022-release

    steps:
      - name: "â³ Clone repo..."
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "ğŸ–¼ï¸ Setup scene..."
        shell: bash
        run: |
          true

      - name: "ğŸ”§ CMake: Configure"
        shell: bash
        run: cmake --preset msvc-2022 -A "${{ matrix.vs_arch }}"

      - name: "ğŸ› ï¸ CMake: Build"
        shell: bash
        run: cmake --build --preset "msvc-2022-release"

      - name: "ğŸ’£ Test um-crypto ..."
        shell: bash
        run: ctest --preset "msvc-2022-release" --output-on-failure

      - name: "ğŸ“¦ Package static libs..."
        shell: bash
        run: |
          DIST_SOURCE="dist/libparakeet-${{ matrix.win_ver }}/"
          mkdir -p "${DIST_SOURCE}/libparakeet"
          cp -R "out/build/$PRESET_NAME/Release" "${DIST_SOURCE}/libparakeet/lib"
          cp -R include "${DIST_SOURCE}/libparakeet"
          cp README.md CHANGELOG.md LICENSE.txt "${DIST_SOURCE}"

      - name: "ğŸš€ Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "libparakeet-${{ matrix.win_ver }}"
          path: dist/

      - name: "ğŸ—œï¸ Packaging"
        working-directory: dist
        shell: pwsh
        run: Compress-Archive "../libparakeet-${{ matrix.win_ver }}.zip" -CompressionLevel Optimal -Path *

      - name: ğŸ“ Draft Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "<to be filled>"
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: "*.zip"
