name: Build (Linux x86_64)

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  schedule:
    # Build once every fortnight
    - cron: "10 4 1,15 * *"

permissions:
  contents: write

jobs:
  build:
    name: "Build Linux Binary"

    runs-on: ubuntu-22.04
    env:
      PRESET_NAME: ninja
      CXX: g++-11

    steps:
      - name: "â³ Clone repo..."
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "ğŸ–¼ï¸ Setup scene..."
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build

      - name: Restore CPM dependencies
        id: cache-cpm-deps
        uses: actions/cache/restore@v3
        with:
          path: |
            out/cache-cpm
            out/build/${{ env.PRESET_NAME }}/_deps
          key: ${{ runner.os }}-cpm-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cpm-${{ hashFiles('CMakeLists.txt') }}
            ${{ runner.os }}-cpm-

      - name: "ğŸ”§ CMake: Configure"
        shell: bash
        run: cmake --preset "${{ env.PRESET_NAME }}"

      - name: "ğŸ› ï¸ CMake: Build"
        shell: bash
        run: cmake --build --preset "${{ env.PRESET_NAME }}-release"

      - name: Save CPM dependencies
        id: cache-cpm-deps-save
        uses: actions/cache/save@v3
        with:
          path: |
            out/cache-cpm
            out/build/${{ env.PRESET_NAME }}/_deps
          key: ${{ steps.cache-cpm-deps.outputs.cache-primary-key }}

      - name: "ğŸ’£ Test um-crypto ..."
        shell: bash
        run: ctest --preset "${{ env.PRESET_NAME }}-release" --output-on-failure

      - name: "ğŸ“¦ Package static libs..."
        shell: bash
        run: |
          DIST_SOURCE="libparakeet-amd64/"
          mkdir -p "${DIST_SOURCE}/libparakeet/lib"
          cp -R "out/build/$PRESET_NAME/Release/"*.a "${DIST_SOURCE}/libparakeet/lib"
          cp -R include "${DIST_SOURCE}/libparakeet"
          cp README.md CHANGELOG.md LICENSE.txt "${DIST_SOURCE}"

      - name: "ğŸ—œï¸ Packaging"
        run: tar zcvf "libparakeet-linux-amd64.tar.gz" libparakeet-amd64

      - name: "ğŸš€ Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: libparakeet-amd64
          path: libparakeet-amd64/

      - name: ğŸ“ Draft Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "<to be filled>"
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: "*.tar.gz"
