name: Code QA
on: [pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    env:
      PRESET_NAME: make

    steps:
      - uses: actions/checkout@v3

      - name: "üñºÔ∏è Setup scene..."
        shell: bash
        run: |
          cmake --preset "${{ env.PRESET_NAME }}"

      - uses: ZedThree/clang-tidy-review@v0.10.1
        id: review
        with:
          cmake_command: "true"
          build_dir: "./out/build/${{ env.PRESET_NAME }}"
          config_file: ".clang-tidy"
