name: Code QA
on: [pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "üñºÔ∏è Setup scene..."
        shell: bash
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
          ./vcpkg/vcpkg install

      - uses: ZedThree/clang-tidy-review@v0.10.1
        id: review
        with:
          cmake_command: cmake --preset ninja
          build_dir: ./out/build/ninja
          config_file: ".clang-tidy"
